site_name: "System Design for Knowledge Discovery"
site_author: "Emma Tosch (etosch@uvm.edu)"
site_description: "Public Course Website for CS295B/CS395B F2021 at University of Vermont"
docs_dir: "src"
use_directory_urls: false
site_url: "https://uvm.edu/~etosch/CS295B-F2021"
repo_url: "https://github.com/etosch/CS295B-F2021"
repo_name: "Github"
edit_uri: "tree/main/src/"
theme:
  name: "readthedocs"
markdown_extensions:
  - attr_list
  - extra
  - sane_lists
  - tables
  - nl2br
nav:
  - 'index.md'
  - 'syllabus.md'
  - 'schedule.md'
  - 'course_project.md'
  - 'scribe_guidelines.md'
extra_css:
  - 'css/style.css' 